apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    containerIPForwarding: Enabled
    bgp: Enabled
    ipPools:
    - allowedUses:
        - Workload
        - Tunnel
      name: default-ipv4-ippool
      disableBGPExport: false
      blockSize: 26
      cidr: 10.244.0.0/16
      encapsulation: None
      natOutgoing: Enabled
      nodeSelector: all()
#---
#apiVersion: projectcalico.org/v3
#kind: IPPool
#metadata:
#  name: external-lb-pool
#spec:
#  cidr: 10.254.0.0/24
#  blockSize: 26
#  natOutgoing: true
#  disabled: false
#  allowedUses:
#    - LoadBalancer
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}