apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-cni-plugin
rules:
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["clusterinformations"]
    verbs: ["get", "list", "watch"]
