apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: linuxserver/plex
        ports:
        - containerPort: 32400
      volumes:
      - name: plex
        persistentVolumeClaim: 
          claimName: nfs-pvc

---
# Service 
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: plex
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
      nodePort: 32400
---
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec: 
  capacity:
    storage: 20Gi
  accessModes: 
  - ReadWriteMany
  nfs:
    path: /srv/nfs/media
    server: 10.0.10.84
---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteMany
